### ISSUE TITLE
Support local sources

### ISSUE THREAD

**Issue by falzm** [mkdeb/mkdeb#8]
It would be nice that `mkdeb` could support "local" sources, i.e. files and directories that would be copied *as-is* in the resulting package (similar to fpm's [dir](https://github.com/jordansissel/fpm/wiki/Source:-dir) source).

**Comment by vbatoufflet** [comment]
Local upstream source folder are now supported through a command looking like:

```
mkdeb build --from path/to/example/src --recipe path/to/example/recipe example=1.2.3
```
